package com.unstampedpages.app.util

/**
 * Maps ISO 4217 currency codes to their commonly used symbols.
 * Falls back to "$" for codes not in the map.
 */
object CurrencySymbols {

    private val symbols: Map<String, String> = mapOf(
        "AED" to "د.إ",
        "AFN" to "؋",
        "ALL" to "L",
        "AMD" to "֏",
        "AOA" to "Kz",
        "ARS" to "$",
        "AUD" to "$",
        "AWG" to "ƒ",
        "AZN" to "₼",
        "BAM" to "KM",
        "BBD" to "$",
        "BDT" to "৳",
        "BGN" to "лв",
        "BHD" to "BD",
        "BIF" to "Fr",
        "BMD" to "$",
        "BND" to "$",
        "BOB" to "Bs.",
        "BRL" to "R$",
        "BSD" to "$",
        "BTN" to "Nu",
        "BWP" to "P",
        "BYN" to "Br",
        "BZD" to "$",
        "CAD" to "$",
        "CDF" to "Fr",
        "CHF" to "Fr",
        "CLP" to "$",
        "CNY" to "¥",
        "COP" to "$",
        "CRC" to "₡",
        "CUP" to "$",
        "CVE" to "$",
        "CZK" to "Kč",
        "DJF" to "Fr",
        "DKK" to "kr",
        "DOP" to "$",
        "DZD" to "دج",
        "EGP" to "£",
        "ERN" to "Nfk",
        "ETB" to "Br",
        "EUR" to "€",
        "FJD" to "$",
        "FKP" to "£",
        "GBP" to "£",
        "GEL" to "₾",
        "GHS" to "₵",
        "GIP" to "£",
        "GMD" to "D",
        "GNF" to "Fr",
        "GTQ" to "Q",
        "GYD" to "$",
        "HKD" to "$",
        "HNL" to "L",
        "HTG" to "G",
        "HUF" to "Ft",
        "IDR" to "Rp",
        "ILS" to "₪",
        "INR" to "₹",
        "IQD" to "ع.د",
        "IRR" to "﷼",
        "ISK" to "kr",
        "JMD" to "$",
        "JOD" to "JD",
        "JPY" to "¥",
        "KES" to "KSh",
        "KGS" to "с",
        "KHR" to "៛",
        "KMF" to "Fr",
        "KPW" to "₩",
        "KRW" to "₩",
        "KWD" to "KD",
        "KYD" to "$",
        "KZT" to "₸",
        "LAK" to "₭",
        "LBP" to "£",
        "LKR" to "₨",
        "LRD" to "$",
        "LSL" to "L",
        "LYD" to "LD",
        "MAD" to "د.م.",
        "MDL" to "L",
        "MGA" to "Ar",
        "MKD" to "ден",
        "MMK" to "K",
        "MNT" to "₮",
        "MRU" to "UM",
        "MUR" to "₨",
        "MVR" to "Rf",
        "MWK" to "MK",
        "MXN" to "$",
        "MYR" to "RM",
        "MZN" to "MT",
        "NAD" to "$",
        "NGN" to "₦",
        "NIO" to "C$",
        "NOK" to "kr",
        "NPR" to "₨",
        "NZD" to "$",
        "OMR" to "﷼",
        "PEN" to "S/",
        "PGK" to "K",
        "PHP" to "₱",
        "PKR" to "₨",
        "PLN" to "zł",
        "PYG" to "₲",
        "QAR" to "﷼",
        "RON" to "lei",
        "RSD" to "din",
        "RUB" to "₽",
        "RWF" to "Fr",
        "SAR" to "﷼",
        "SBD" to "$",
        "SCR" to "₨",
        "SDG" to "£",
        "SEK" to "kr",
        "SGD" to "$",
        "SHP" to "£",
        "SLE" to "Le",
        "SLS" to "Sl",
        "SOS" to "Sh",
        "SRD" to "$",
        "SSP" to "£",
        "STN" to "Db",
        "SYP" to "£",
        "SZL" to "L",
        "THB" to "฿",
        "TJS" to "SM",
        "TMT" to "T",
        "TND" to "DT",
        "TOP" to "T$",
        "TRY" to "₺",
        "TTD" to "$",
        "TWD" to "$",
        "TZS" to "Sh",
        "UAH" to "₴",
        "UGX" to "Sh",
        "USD" to "$",
        "UYU" to "$",
        "UZS" to "лв",
        "VES" to "Bs.S",
        "VND" to "₫",
        "VUV" to "Vt",
        "WST" to "T",
        "XAF" to "Fr",
        "XCD" to "$",
        "XOF" to "Fr",
        "XPF" to "Fr",
        "YER" to "﷼",
        "ZAR" to "R",
        "ZMW" to "ZK"
    )

    /**
     * Returns the currency symbol for the given ISO 4217 [currencyCode],
     * or "$" if the code is not recognised.
     */
    fun getSymbol(currencyCode: String): String = symbols[currencyCode] ?: "$"
}
